.\" Process this file with
.\" groff -man -Tascii tsh.1
.\"
.TH TSH 1 "OCTOBER 2009" "NU EECS 343" "NU EECS 343 - Operating Systems - Fall 2009"
.SH NAME
tsh \- A tiny shell
.SH SYNOPSIS
.B tsh
.SH DESCRIPTION
.B tsh
description... Include the features that you implemented
.SH BUILT-IN COMMANDS
.IP exit
Quit tsh
.SH DESIGN APPROACH
Write about your design approach, challenges, and whether you went for
the extra credit here.
.SH AUTHOR
Your names, netids and emails here
